# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sola.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(200, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.okButton = QtWidgets.QPushButton(Dialog)
        self.okButton.setGeometry(QtCore.QRect(100, 350, 75, 24))
        self.okButton.setCheckable(False)
        self.okButton.setObjectName("okButton")
        self.onOffButton = QtWidgets.QPushButton(Dialog)
        self.onOffButton.setGeometry(QtCore.QRect(100, 100, 75, 24))
        self.onOffButton.setCheckable(True)
        self.onOffButton.setObjectName("onOffButton")
        self.inputPower = QtWidgets.QLineEdit(Dialog)
        self.inputPower.setGeometry(QtCore.QRect(100, 200, 75, 25))
        self.inputPower.setObjectName("inputPower")
        self.powerSlider = QtWidgets.QSlider(Dialog)
        self.powerSlider.setGeometry(QtCore.QRect(30, 50, 30, 300))
        self.powerSlider.setObjectName("powerSlider")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "SOLA control"))
        self.okButton.setText(_translate("Dialog", "Ok"))
        self.onOffButton.setText(_translate("Dialog", "Off"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
